name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: WebApp Build
      run: go build

    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --local-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}